class ResponseCodes {
  static CREATE_SUCCESS = "CREATE_SUCCESS";
  static CREATE_FAILED = "CREATE_FAILED";
  static GET_SUCCESS = "GET_SUCCESS";
  static UPDATE_SUCCESS = "UPDATE_SUCCESS";
  static UPDATE_FAILED = "UPDATE_FAILED";
  static DELETE_SUCCESS = "DELETE_SUCCESS";
  static DELETE_FAILED = "DELETE_FAILED";
  static USER_NOT_FOUND = "USER_NOT_FOUND";
  static OTP_IS_INCORRECT = "OTP_IS_INCORRECT";
  static VERIFY_FAILED = "VERIFY_FAILED";
  static VERIFY_SUCCESS = "VERIFY_SUCCESS";
  static SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG";
  static VERIFICATION_OTP_SENT = "VERIFICATION_OTP_SENT";
  static INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
  static INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
  static LOGIN_SUCCESS = "LOGIN_SUCCESS";
  static USER_VERIFIED_PENDING = "USER_VERIFIED_PENDING";
  static UNAUTHORIZED = "UNAUTHORIZED";
  static INVALID_TOKEN = "INVALID_TOKEN";
  static MAIL_SENDED_FAILED = "MAIL_SENDED_FAILED";
  static MAIL_SENDED_SUCCESS = "MAIL_SENDED_SUCCESS";
  static PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
  static TOKEN_EXPIRED = "TOKEN_EXPIRED";
  static EXIST_USER = "EXIST_USER"
}
export default ResponseCodes;
